rebuild Singularity containers and Makefile

diff --git a/containers/Makefile b/containers/Makefile
--- a/containers/Makefile
+++ b/containers/Makefile
@@ -1,12 +1,38 @@
 SHELL:=/bin/bash
 VAR=
+.PHONY: $(VAR)
 none:
 
-.PHONY: $(VAR)
-
+# ~~~~~ VALIDATION ~~~~~ #
 check-Docker:
-	docker --version > /dev/null 2>&1 || { echo "ERROR: 'docker' not found" && exit 1 ; }
+	@docker --version > /dev/null 2>&1 || { echo "ERROR: 'docker' not found" && exit 1 ; }
 
+check-vagrant:
+	@vagrant -v >/dev/null 2>&1 || { echo "ERROR: 'docker' not found" && exit 1 ; }
+
+check-var:
+	@test $(VAR) || (echo ">>> ERROR: VAR must be set for this; 'make <recipe> VAR=dir'" ; exit 1)
+
+check-var-dir:
+	@[ ! -d "$(VAR)" ] && { echo ">>> ERROR: VAR '$(VAR)' is not a directory" ; exit 1 ; } || :
+
+check-singularityfile:
+	@[ ! -f "$(SINGULARITYFILE)" ] && { echo ">>> ERROR: Singularity file '$(SINGULARITYFILE)' does not exist" ; exit 1 ; } || :
+
+check-singularityimage:
+	@[ ! -f "$(IMG)" ] && { echo ">>> ERROR: Singularity image file '$(IMG)' does not exist" ; exit 1 ; } || :
+
+# ~~~~~~ SETUP ~~~~~ #
+Vagrantfile:
+	vagrant init singularityware/singularity-2.4
+
+# ~~~~~~ CLEANUP ~~~~~ #
+# seems to fix sporadic errors that arise when using Singularity inside Vagrant...
+clean-vagrant:
+	[ -d .vagrant ] && rm -rf .vagrant || :
+
+
+# ~~~~~ BUILD ALL ~~~~~ #
 build-all-Docker: check-Docker
 	for item in $$(find . -maxdepth 2 -mindepth 2 -type f -name "Dockerfile" -exec dirname {} \; | cut -d '/' -f2- | xargs); \
 	do \
@@ -30,3 +56,36 @@ build-all-Singularity:
 	do \
 	make -f Singularity.makefile build VAR=$$item ; \
 	done
+
+# ~~~~~ SINGULARITY ~~~~~ #
+SINGULARITYFILE:=$(VAR)/Singularity.$(VAR)
+IMG:=$(VAR)/$(VAR).simg
+TEST:=
+singularity-build:
+	@$(MAKE) check-var
+	@$(MAKE) check-var-dir
+	@$(MAKE) check-singularityfile
+	@echo ">>> Setting up to build Singularity image in directory: $(VAR)"
+	@[ -f "$(IMG)" ] && { echo ">>> Removing previous image file: $(IMG)" ; rm -f "$(IMG)" ; wait $$! ; } ; \
+	echo ">>> Output file will be: $(IMG)" && \
+	vagrant up build && \
+	vagrant ssh build -c "cd /vagrant && sudo singularity build $(IMG) $(SINGULARITYFILE)" && \
+	[ -n "$(TEST)" ] && $(MAKE) test || :
+
+singularity-test:
+	@$(MAKE) check-var
+	@$(MAKE) check-var-dir
+	@$(MAKE) check-singularityimage
+	@echo ">>> Starting Vagrant..." && \
+	vagrant up test && \
+	vagrant ssh test -c "singularity shell /vagrant/$(IMG)"
+
+# copy all image files to Big Purple HPC
+USER:=$(shell echo $$USER)
+REMOTE:=bigpurple.nyumc.org
+REMOTEDIR:=/gpfs/home/$(USER)/containers/NGS580-nf
+singularity-sync:
+	@$(MAKE) check-var
+	@$(MAKE) check-singularityimage
+	@echo 'command:'
+	@echo 'rsync --dry-run -vrhP -e ssh $(IMG) $(USER)@$(REMOTE):$(REMOTEDIR)'
